source 'https://rubygems.org'

gem 'bundler'
gem 'asciidoctor'
gem 'asciidoctor-pdf', ">= 1.5.0.alpha.15"
gem 'asciidoctor-revealjs' # latest released version
gem 'coderay'
gem 'rouge'
gem 'pygments.rb'
gem 'filewatcher'
gem 'asciidoctor-diagram'
gem 'prawn', ">= 2.2.0"
