asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/02-es6-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/03-create-react-app-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/04-components-and-views-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/05-components-state-and-events-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/06-advanced-components-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/07-routing-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/08-forms-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/09-redux-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/10-async-redux-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/11-ajax-lab.adoc
asciidoctor-pdf -a toc -a experimental=true -r asciidoctor-diagram -d book -D ./pdf -a pdf-style=./custom-theme.yml src/final-thoughts.adoc
